name: ultrack-multi-color
channels:
  - gurobi
  - rapidsai
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - cellpose  #  conda install -c conda-forge cellpose
  - coin-or-cbc  #  conda install -c conda-forge coin-or-cbc
  - cucim  #  conda install -c rapidsai-nightly cucim
  - cpuonly
  - gurobi  #  conda install -c gurobi gurobi
  - jupyter
  - pip
  - pyqt
  - seaborn
  - pip:
    - napari==0.4.18
    - traccuracy
    - napari-arboretum
    - pyift

#only need to install:
pip install pyift
python -m pip install cellpose
pip install tensorflow-cpu
pip install cchardet
python -m pip install gurobipy
pip install chardet
pip install -U --force-reinstall charset-normalizer  
